name: Create Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout repo files
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Build mod
        run: dotnet build OWCHT/OWCHT.csproj -c Release

      - name: Read manifest.json
        id: read-manifest
        run: |
          $manifest = Get-Content ./OWCHT/manifest.json -Raw | ConvertFrom-Json
          echo "version=$($manifest.version)" >> $env:GITHUB_OUTPUT
          echo "uniqueName=$($manifest.uniqueName)" >> $env:GITHUB_OUTPUT

      - name: Check for existing tag
        id: checkTag
        run: |
          $tag = "v${{ steps.read-manifest.outputs.version }}"
          $result = git ls-remote --tags origin "refs/tags/$tag"
          Write-Host "ls-remote result: $result"
          if ($result) {
            Write-Host "Tag exists, skipping release"
            echo "exists=true" >> $env:GITHUB_OUTPUT
          } else {
            Write-Host "Tag not found, will create release"
            echo "exists=false" >> $env:GITHUB_OUTPUT
          }
          Write-Host "exists output set"

      - name: Package mod
        if: ${{ steps.read-manifest.outputs.version != '0.0.0' && steps.checkTag.outputs.exists == 'false' }}
        run: |
          $uniqueName = "${{ steps.read-manifest.outputs.uniqueName }}"
          New-Item -ItemType Directory -Path $uniqueName
          Copy-Item OWCHT/bin/Release/OWCHT.dll $uniqueName/
          Copy-Item OWCHT/manifest.json $uniqueName/
          Copy-Item OWCHT/default-config.json $uniqueName/
          Copy-Item -Recurse OWCHT/Assets $uniqueName/
          Copy-Item "OWCHT/Translation_Text/Translation_TC.xml" "$uniqueName/Translation.xml"
          Compress-Archive -Path $uniqueName -DestinationPath "$uniqueName.zip"

      - name: Create Release
        uses: "ncipollo/release-action@v1"
        if: ${{ steps.read-manifest.outputs.version != '0.0.0' && steps.checkTag.outputs.exists == 'false' }}
        with:
          allowUpdates: true
          commit: ${{ github.ref_name }}
          tag: "v${{ steps.read-manifest.outputs.version }}"
          name: "Version ${{ steps.read-manifest.outputs.version }}"
          omitBodyDuringUpdate: true
          artifacts: "${{ steps.read-manifest.outputs.uniqueName }}.zip"
          draft: true
          prerelease: false
